In [6]:
import numpy as np
import pandas as pd
import os
import string

In [7]:
dataset = pd.read_csv("plant_village.csv")

In [8]:
dataset.head(30)

Unnamed: 0      mean_r      mean_g      mean_b   stddev_r   stddev_g  \
0            0   92.509664  123.772174  115.994881  33.995882  30.674940   
1            0   82.475441   88.820207   98.832425  37.661143  34.035775   
2            0  114.306123  126.906421   98.876777  29.471802  23.918051   
3            0  125.301169  134.151762  124.036178  51.008068  44.354188   
4            0  111.720339  115.258361  111.063832  55.794415  47.888428   
5            0  106.409224  108.721954  130.981618  24.463582  18.143031   
6            0   93.097803  107.912752  100.017474  43.902772  39.761931   
7            0  104.429062  111.851273  109.931693  56.930254  50.564104   
8            0  129.404691  138.095249  121.772908  49.042387  42.704688   
9            0  109.457106  108.060377  111.986971  36.088445  27.606863   
10           0  100.748657  115.644518  124.911171  35.533203  30.743041   
11           0   96.753229  114.159723   99.598286  47.272564  42.762870   
12           0  107.108624  110.356870  115.636692  26.179083  20.273846   
13           0  104.822735  113.308867  105.186365  57.773281  50.733442   
14           0   84.590302   97.103658   92.933624  32.910126  30.717050   
15           0  117.633999  126.442210  120.935448  35.316128  27.192726   
16           0  123.295911  131.071122  113.598594  36.306309  25.858205   
17           0  111.600364  131.313225  104.654238  48.578774  39.881202   
18           0  101.071925  108.062248  118.248738  30.885113  28.050737   
19           0   67.049130   91.190924   92.909144  34.337304  29.057027   
20           0   91.755909   99.267185   92.280921  25.590142  17.623805   
21           0   92.549419  109.466051  104.976524  30.231139  23.137224   
22           0  102.255659  108.301202  115.961584  25.786721  22.587009   
23           0   96.176072   98.394686   87.584619  32.604086  28.690745   
24           0  134.436626  148.706411  120.161933  41.964471  37.070785   
25           0  102.454105  118.181223   86.756313  51.570543  45.054346   
26           0   94.210263  107.324541   94.931228  45.948648  38.578525   
27           0   95.552522  109.781215   92.734955  47.501745  36.289773   
28           0  122.843872  134.987061  117.638576  43.928392  33.792253   
29           0   92.473375   96.071259  105.471710  24.395554  17.523767   

     stddev_b     contrast  correlation  inverse_difference_moments    entropy  
0   37.516841   141.245826     0.926668                    0.206899  11.680282  
1   46.192337   223.679241     0.912155                    0.142005  12.679627  
2   37.849226    54.678367     0.957859                    0.342370  10.758493  
3   59.283671  1158.188428     0.731148                    0.061645  14.094453  
4   64.473558   506.024359     0.903427                    0.130418  13.272624  
5   38.716076   108.735126     0.875595                    0.196078  11.287765  
6   52.662111   254.071102     0.925355                    0.128134  12.951365  
7   64.346819   704.116973     0.874579                    0.129248  13.605420  
8   58.295191   499.104008     0.877811                    0.111657  12.977689  
9   52.477709    43.903045     0.976820                    0.353223  10.693878  
10  52.060722    90.000663     0.959836                    0.238851  11.431990  
11  57.401277   626.594593     0.842039                    0.128690  13.410290  
12  39.608323    32.715367     0.964667                    0.415945   9.924318  
13  66.679965  1124.616829     0.804476                    0.082395  14.140149  
14  48.049434   150.167855     0.926191                    0.162081  12.136934  
15  47.311172    69.492211     0.962514                    0.226219  11.277493  
16  41.131928   229.035323     0.868394                    0.109622  12.468313  
17  59.459647   358.663392     0.899243                    0.143802  12.775604  
18  44.315640    63.452590     0.963256                    0.255381  11.331872  
19  39.903054    89.939104 

In [9]:
type(dataset)

pandas.core.frame.DataFrame

In [10]:
maindir = r'C:\Users\Gujjar Boy\Downloads\Programs\A Final Year Project'
ds_path = maindir + "\\crowdai"
img_files = os.listdir(ds_path)

In [11]:
img_files[0]

'1000.jpg'

In [12]:
breakpoints = [1000,1269,1270,1549,1550,1673,1674,2386,2387,2972,2973,3482,3483,3840,3841,4031,4032,4550,4551,4924,4925,5369,5370,5845,5846,6397,6398,6817,6818,6988,6989,9309,9310,9999]
print(len(breakpoints))

34


In [13]:

target_list = []
for file in img_files:
    target_num = int(file.split(".")[0])
    #print(target_num)
    flag = 0
    i = 0 
    for i in range(0,len(breakpoints),2):
        if((target_num >= breakpoints[i]) and (target_num <= breakpoints[i+1])):
            flag = 1
            break
    
    if(flag==1):
        target = int((i/2))
        target_list.append(target)

In [14]:
y = np.array(target_list)
y

array([ 0,  0,  0, ..., 16, 16, 16])

In [15]:

X = dataset.iloc[:,1:]

In [16]:
X.head(5)

mean_r      mean_g      mean_b   stddev_r   stddev_g   stddev_b  \
0   92.509664  123.772174  115.994881  33.995882  30.674940  37.516841   
1   82.475441   88.820207   98.832425  37.661143  34.035775  46.192337   
2  114.306123  126.906421   98.876777  29.471802  23.918051  37.849226   
3  125.301169  134.151762  124.036178  51.008068  44.354188  59.283671   
4  111.720339  115.258361  111.063832  55.794415  47.888428  64.473558   

      contrast  correlation  inverse_difference_moments    entropy  
0   141.245826     0.926668                    0.206899  11.680282  
1   223.679241     0.912155                    0.142005  12.679627  
2    54.678367     0.957859                    0.342370  10.758493  
3  1158.188428     0.731148                    0.061645  14.094453  
4   506.024359     0.903427                    0.130418  13.272624

In [15]:
y[0:5]

array([0, 0, 0, 0, 0])

In [16]:
#Train test split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 142)

In [19]:
X_train.head(5)

mean_r      mean_g      mean_b   stddev_r   stddev_g   stddev_b  \
3964  110.072104  159.233719  131.961972  27.140586  24.466712  27.389126   
1067   82.564043   98.890889  109.420928  39.298992  38.468545  51.228020   
2401  115.825688  118.737737   94.857721  38.179354  36.353173  44.758595   
4766  104.578959  118.873818   90.257840  68.741033  52.769674  68.411842   
101   139.361927  145.180421  137.465901  65.475447  61.570231  69.279968   

        contrast  correlation  inverse_difference_moments    entropy  
3964   95.133817     0.925400                    0.178761  11.490641  
1067  164.482505     0.947380                    0.155684  12.454126  
2401   57.467823     0.978724                    0.289971  11.277982  
4766  566.730354     0.917908                    0.083414  13.676810  
101   817.508787     0.893893                    0.130472  13.343331

In [20]:
X_train.shape

(6299, 10)

In [21]:
y_train[0:5]

array([10,  3,  5, 11,  0])

In [22]:
#Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [25]:
X_train[0:2]

array([[-0.27135619,  1.72574766,  1.297164  , -1.25987687, -1.07737475,
        -1.74538858, -0.81620459,  0.21267105, -0.11418883, -0.47311907],
       [-1.58551432, -1.06029926,  0.44147284, -0.37957632,  0.01614473,
         0.1912474 , -0.56039989,  0.57567253, -0.32973539,  0.25786502]])

In [26]:
y_train[0:2]

array([10,  3])

In [27]:
#Applying SVM classifier model

In [28]:
from sklearn import svm

In [29]:
clf = svm.SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
clf.fit(X_train,y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
y_pred = clf.predict(X_test)

In [31]:
from sklearn import metrics

In [32]:
metrics.accuracy_score(y_test, y_pred)

0.8314814814814815

In [33]:
from sklearn.model_selection import GridSearchCV


In [36]:
parameters = [{'kernel': ['rbf'],
               'gamma': [1e-4, 1e-3, 0.01, 0.1, 0.2, 0.5],
               'C': [1, 10, 100, 1000]},
              {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}
             ]

In [37]:
svm_clf = GridSearchCV(svm.SVC(decision_function_shape='ovr'), parameters, cv=5)
svm_clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'kernel': ['rbf'], 'gamma': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.5], 'C': [1, 10, 100, 1000]}, {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [38]:
svm_clf.best_params_

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
print(metrics.classification_report(y_test, y_pred))

In [46]:
int(int(clf.predict(X_train[0:1])))

3

In [39]:
clf = svm.SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
clf.fit(X_train,y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
y_pred = clf.predict(X_test)

In [41]:
metrics.accuracy_score(y_test, y_pred)

0.8688888888888889